### ISSUE TITLE
python --version showing a different installation / not the pyenv version

### ISSUE THREAD

**Issue by DucVanNgo** [lewagon/data-setup#234]
I suggest to add the following lines as `Troubleshooting` in case `python --version` doesn't output the correct python version for the bootcamp. A lot of students had previously installed anaconda and `python --version` refers to the anaconda install without adding the lines below. 

Below's code and restarting the terminal should fix this. Source: https://gist.github.com/josemarimanio/9e0c177c90dee97808bad163587e80f8

`export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"

plugin=(pyenv)  # don't replace but add it to plugin line

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"`

**Comment by gmanchon** [comment]
Thanks for reporting @DucVanNgo ! 🙏

These lines correspond to the content of setup dotfiles [.zshrc](https://github.com/lewagon/dotfiles/blob/master/zshrc#:~:text=eval%20%22%24(pyenv%20init%20%2D)%22%20%26%26%20eval%20%22%24(pyenv%20virtualenv%2Dinit) and [.zprofile](https://github.com/lewagon/dotfiles/blob/master/zprofile#:~:text=export%20PYENV_ROOT%3D,%24PATH%22) files, unless PIPENV_PYTHON which we do not use.

We are addressing the issue of anaconda in this ticket https://github.com/lewagon/data-setup/issues/177 in order to deactivate conda so that it does not take precedence over pyenv.
