### ISSUE TITLE
Apple Silicon - students need to manually install tensorflow-macos

### ISSUE THREAD

**Issue by julesvanrie** [lewagon/data-setup#239]
**Step**: Python packages

**Platform**: Apple Silicon M1 and M2

**Problem**: `tensorflow-macos` is not installed automatically

When doing the second check under  _Python setup check up_, it is detected that `tensorflow-macos` is not installed, and students are then requested to install it separately.

This works, and doesn't result in problems, but it would be nice to avoid this.

**Potential solution**:

The new common `requirements.txt` checks against `platform_machine == "aarch64"`. I think this should become `platform_machine == "arm64"`.

On Apple Silicon when checking `arch` in the terminal, or `import platform; platform.machine()` (which corresponds to `platform_machine` in `requirements.txt`) both return `arm64`.

I guess the same applies to some other packages that use the same check against Apple Silicon.

**Comment by gmanchon** [comment]
Hello @julesvanrie 👋, thanks for reporting 🙏 

The platform_machine instructions are going to be removed from the next version of the data setup which should make it easier for pip to deal with the requirements file

The setup is also going to be updated so that Apple Intel uses `tensorflow` whereas Apple Silicon uses `tensorflow-macos`

I just tested the check script on both machine types and it seems to work correctly :

```
zsh -c "$(curl -fsSL https://raw.githubusercontent.com/lewagon/data-setup/master/checks/pip_check.sh)"
```

Does this solve your issue ?

**Comment by julesvanrie** [comment]
Was a suggestion for improvement, but I understand that it will be solved in next release anyway thus. So for me it's closed 👍🏼
