### ISSUE TITLE
Extra quotes cause browser to not pop up on jupyter notebook command

### ISSUE THREAD

**Issue by gitgithan** [lewagon/data-setup#248]
![image](https://user-images.githubusercontent.com/29853829/198345283-95040438-ac88-4b8f-b25b-cbada2aa13a7.png)
`echo $BROWSER` shows the path in double quotes. There's no new tab popping up in chrome.

I had to manually delete the single quotes wrapping the double quotes in zshrc, after that the tab pops up on `jupyter notebook` and `echo $BROWSER` shows the path without double quotes. 

Another issue is the >> append did not append to a new line, but appended to a previous block of lines that were commented out, so the echo was treated as a comment and did not take effect, i had to manually arrange it to the new line

**Comment by julesvanrie** [comment]
This one is still happening. Windows setup to be precise. All users had it today (6). 

Removing single quotes indeed solved the problem.

**Comment by gmanchon** [comment]
[slack thread](https://lewagon-alumni.slack.com/archives/C015E0C601F/p1673967846249909?thread_ts=1673868245.272259&cid=C015E0C601F)

**Comment by julesvanrie** [comment]
Spent a bit more time on this (many Windows laptops in my batch).

The problem only occurs when a `BROWSER` env variable is added to `.zshrc`. 

> In the setup, we `export BROWSER` only for `gh`, not for `jupyter`. Later, when students setup dotfiles, we don't have the `export BROWSER` anymore. On some laptops this works fine (mine doesn't need `BROWSER` and opens my browser nicely when using `gh browse` and `jupyter notebook`. But on some students' laptops this doesn't work, and they need `BROWSER` to be set. If then the line is used as during the setup, it doesn't work because of the extra quotes.

Underlying problem is that `gh` and `jupyter notebook` expect the path in a different format:
- `gh` needs `export BROWSER="'/mnt/c/Program Files/Google/Chrome/Application/chrome.exe'"` (mind the extra quotes)
- `jupyter notebook` needs `export BROWSER="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"` (no extra quotes)

Fortunately `gh` now supports an env variable called `GH_BROWSER`, which has higher prio than `BROWSER`.

So, adding the following to .zshrc seems to always work:

``` bash
# Browser
export BROWSER="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
export GH_BROWSER="'/mnt/c/Program Files/Google/Chrome/Application/chrome.exe'"
```

Could be useful to add this to the end of the setup?
Or, in the first part of the setup, where `BROWSER` is exported for use by `gh`, maybe replace it with `GH_BROWSER` to avoid confusion.
