### ISSUE TITLE
Dotfiles / Setup new laptop

### ISSUE THREAD

**Issue by njric** [lewagon/data-setup#290]
When setting up a new laptop doc ask to fork from lewagon/dotfiles. Shouldn't it be your_github_username/dotfiles ?

https://github.com/lewagon/data-setup/blob/master/macOS.md?plain=1#L471

**Comment by julesvanrie** [comment]
Hi @njric, Thanks for reporting.
It's actually fine like this. Checked it again to confirm my earlier understanding.

It seems a bit counterintuitive, but if the fork already exist then the command we have:
```bash
gh repo fork lewagon/dotfiles --clone
```
will actually just clone your own fork.

Alternatively we could indeed have included this instead:
```bash
gh repo clone $GITHUB_USERNAME/dotfiles
```
Because that is what actually happens.

But I'm going to keep it like it is. Because now we have the same commands for both cases, which makes it easier for teachers to assist students.
