### ISSUE TITLE
Tensorflow - Illegal hardware instruction

### ISSUE THREAD

**Issue by zzuziak** [lewagon/data-setup#87]
When running the check for `pandas`, `scikit` and `Tensorflow` the following message comes up (WSL Student):

![image](https://user-images.githubusercontent.com/39556343/114378091-a5d4a980-9b87-11eb-9887-7cf7a8110e42.png)

After digging into it we followed this [article](https://tech.amikelive.com/node-887/how-to-resolve-error-illegal-instruction-core-dumped-when-running-import-tensorflow-in-a-python-program/), it seems that his computer is missing AVX support. Downgrading to Tensorflow 1.5 would require Python 3.7. Building from source might not be stable, but we could try that.

For now we skipped Tensorflow installation and just in case he will run it on Google Colab. 
Any solution would be appreciated!

**Comment by Bruncky** [comment]
So, I’ve been trying a few things here so far. Any opinions/corrections/suggestions are always welcome!


### Using Python 3.9.2 (only version that works natively with M1) + native Homebrew PyEnv

No good. NumPy isn’t compatible with 3.9.2 yet, and in their repo they state that they still need to do a lot of testing before it starts working. Compiling it from source is no good, since many of their tests are failing and it would take way longer for us to fix those errors ourselves (don’t even know where to being) than for them to do it. If even NumPy doesn’t work, there’s no point in trying to install TensorFlow. Let’s just wait!


### Using patched Python 3.8.6 + native Homebrew PyEnv

No good either. The only way to install anything below 3.9.2 on native PyEnv is with patches, so that’s why I needed the [patched 3.8.6](https://github.com/pyenv/pyenv/issues/1768#issuecomment-753756051), but no matter what I do, it’s always missing the `lzma` module. This can be ignored for about the first two weeks of the bootcamp, but will then start causing many issues which can likely not be worked around. It’s the same as above, if we can’t even get Python itself to work (NumPy at least works here), there’s no point in using it at all. _I still tried installing TensorFlow anyways, but that also doesn’t work._


### Using Python 3.8.6 + Intel Homebrew PyEnv + Apple’s own TensorFlow adaptation

This is obviously what we’ve been using so far, so we know that this environment works in general. This is also what sparked this whole research.

The normal TensorFlow on PyPI doesn’t work here, whenever you import it you get the `illegal hardware instruction python pip_check.py` error. The error basically means that it’s trying to use an Intel instruction set on an M1 (ARM) CPU, and that’s not possible because those are two fundamentally different CPU architectures, hence “illegal instruction”.

(Almost) lucky for us, Apple has an [official repo](https://github.com/apple/tensorflow_macos) on GitHub where they have their own adaptation of TensorFlow that works on M1. The problem is that it only works on 3.9.2 with native Homebrew/PyEnv…which brings us back to the first case where NumPy — and everything that is based on it — doesn’t work. It’s still in Alpha (v0.1-alpha3), though, so they might actually get it working below 3.9.2, but I think that’s unlikely. They have no reason to do that, since the tendency is that people will move on to 3.9 at some point anyway. Moreover, if the NumPy people ship a 3.9.2 compatible version, then we would be able to switch to 3.9.2 and use Apple’s TF adaptation, so they’re definitely not making it work below 3.9.2 in my opinion.

On another note, it’s technically possible to make PyPI’s TF work on M1 if you compile it from source. I think this option is 120% not viable for students, because the codebase alone is huge, and compiling/building the package yourself takes up GBs worth of storage…and about 3h for me (and it wasn't even 100% finished). We could think about doing what they do, which is basically compile it once on an M1 machine and make the wheel available for students, but whether that's worth doing instead of just using Google Collab remains up for discussion. We would also have to take responsibility for any issues that may arise here, which is time we may not be able to allocate to it.

Any input is super welcome, cheers!

**Comment by brunolajoie** [comment]
Thanks so much for digging!

One other option would be to use the free gcp credits to startup a _Google Cloud AI Notebook_ instance for the student, so that he/she has access to JupyterLab with permanent storage (4€/month for 100Go) on which to clone data-challenge-week6.

The GPU is not accessible via free credits, but the CPU only VM is cheap.

**Comment by cedricmjohn** [comment]
Have you given some thoughts about installing Apple's tensor-flow metal pluggable extension? Would this work?
https://developer.apple.com/metal/tensorflow-plugin/

**Comment by Bruncky** [comment]
I haven't looked into this, but it seems that this would work only with a Conda environment. I tried installing `tensorflow-macos` a few times (recently even), but sadly had no luck. As of last week I was able to install everything we use on my M1 and Python 3.9.2, except for TensorFlow 😢

**Comment by cedricmjohn** [comment]
I can confirm that on an intel chip Mac it runs on plain-vanilla Python 3.8 in Le Wagon environment. But you do bring a good point: Apple’s own installation instruction seems to suggest using a conda env for M1’s! This makes me suspect that conda works better on M1 chips in general. Have you though of a conda branch for Le Wagon students on M1 chips? Maybe worth a test? Before joining Le Wagon I ran everything on Anaconda Python and never had an issue with it. It is more bulky and all, but if it could solve some current issues it might be worth it for now?

**Comment by Bruncky** [comment]
> Have you though of a conda branch for Le Wagon students on M1 chips?

That's a fair suggestion. I'll see if I can't find a streamlined way to set up a Conda env (possibly starting from one of the less bloated base versions) so I can suggest this to the dev team. Thanks for the input!

**Comment by brunolajoie** [comment]
We don't have a lot of M1 at the moment on LW dev team so it's hard for us to try, but if someone with M1 actually managed to make it work, let us know 🙏

**Comment by bdepebhe** [comment]
a simple `pip install tensorflow-macos` worked for me, but I have no idea why !

**Comment by cedricmjohn** [comment]
Are you on an M1 or an intel chip? What you describe works on intels but I
don’t have an M1 computer to try.

**Comment by bdepebhe** [comment]
M1. I used to switch to conda/miniforge+tensorflow when I teached DL, but today I had the surprise to see tf work on the wagon pyenv environment after running pip install `tensorflow-macos`
Then a warning about tf not able to use CPU appeared when I tested tf. So I tried `tensorflow-metal` and everything seems ok

**Comment by cedricmjohn** [comment]
That’s great news!!!

**Comment by Bruncky** [comment]
As @bdepebhe mentioned, I just tried the same on my M1 MBP and it worked like a charm. I ran one of the solution notebooks from the DL week from top to bottom with 0 issues, so great news for us!

@brunolajoie ☝️

**Comment by krokrob** [comment]
Thank you very much @bdepebhe @Bruncky I'm gonna update the `data-setup` in that way!

**Comment by bdepebhe** [comment]
Do you want to add also something for making a docker builder to make amd64 images ? I posted my solution on slack. If you want I can reset my config and describe step-by-step the process to have buildx run

**Comment by cedricmjohn** [comment]
Would it not be easier to have a pre-made Le Wagon amd64 image that the students can use directly, rather than make it from scratch? Or is this not technically feasible?

**Comment by bdepebhe** [comment]
You mean an image of the taxifare API ? I think the all point of the data engineering week is to have the students make the complete chain from tuesday to friday with their own code.
Or do you mean a pre-made builder image ? I can explore this second option, or just retrieve the couple of shell commands that I found on some stackoverflow when I made my custom setup, and that make this builder container

**Comment by cedricmjohn** [comment]
I did mean the pre-made builder image! :) This would be a step unique to M1 users, so making it a little easier for them would allow a more level playing field for all students. Just a thought...
